# =================== CONFIGURACIONES (editar según necesidad) ===================
# WEB_PORT: puerto host para Moodle (HTTP). Se usa 8080 para mantener "el actual".
# DB_HOST_PORT: puerto host NO estándar para MariaDB (p.e. 3307).
# Volúmenes:
#   ./veco/moodle      -> código Moodle (bind mount)
#   ./veco/moodledata  -> datos Moodle (subidas, caches)
#   ./veco/db          -> datos MariaDB
# ===============================================================================
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodlepass
      - MYSQL_ROOT_PASSWORD=rootpass
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./veco/db:/var/lib/mysql
    ports:
      # Expuesto en puerto NO estándar del host para administración/desarrollo
      - "3307:3306"

  web:
    image: moodlehq/moodle-php-apache:8.2
    depends_on: [db]
    restart: unless-stopped
    environment:
      - MOODLE_DOCKER_DBTYPE=mariadb
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=moodlepass
    volumes:
      - ./veco/moodle:/var/www/html
      - ./veco/moodledata:/var/moodledata
    ports:
      # Mantener "el actual" (8080). Si quiere 8081, cambie a "8081:80"
      - "8080:80"

  cron:
    image: moodlehq/moodle-php-apache:8.2
    depends_on: [web]
    restart: unless-stopped
    environment:
      - MOODLE_DOCKER_DBTYPE=mariadb
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=moodlepass
    volumes:
      - ./veco/moodle:/var/www/html
      - ./veco/moodledata:/var/moodledata
    entrypoint: [ "bash", "-lc", "while true; do php /var/www/html/admin/cli/cron.php; sleep 60; done" ]

  pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on: [db]
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=0
      - UPLOAD_LIMIT=512M
    ports:
      # phpMyAdmin del stack Moodle. Use un puerto libre (p.e. 8083) para evitar conflicto con Lucy.
      - "8083:80"

# =================== NOTAS DE PRODUCCIÓN ===================
# - Considere poner certificados HTTPS delante (reverse proxy).
# - Restrinja la exposición de MariaDB si no necesita acceso externo.
# - Realice backups del volumen ./veco/db con el contenedor detenido.
# ===============================================================================
