services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodlepass
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - ./veco/db:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
      - "127.0.0.1:3306:3306"

  web:
    image: moodlehq/moodle-php-apache:8.2
    depends_on: [db]
    restart: unless-stopped
    environment:
      - MOODLE_DOCKER_DBTYPE=mariadb
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=moodlepass
    volumes:
      - ./veco/moodle:/var/www/html
      - ./veco/moodledata:/var/moodledata
    ports:
      - "8080:80"

  cron:
    image: moodlehq/moodle-php-apache:8.2
    depends_on: [web]
    restart: unless-stopped
    volumes:
      - ./veco/moodle:/var/www/html
      - ./veco/moodledata:/var/moodledata
    entrypoint: [ "bash", "-lc", "while true; do php /var/www/html/admin/cli/cron.php; sleep 60; done" ]

  pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on: [db]
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=512M
      - PMA_ARBITRARY=0
    ports:
      - "8082:80"

  # === Lucy todo-en-uno (PHP + Composer + Node/Vite) ===
  lucy:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    user: "10001:10001"
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - PHP_DATE_TIMEZONE=America/Argentina/Cordoba
      - PHP_UPLOAD_MAX_FILESIZE=256M
      - PHP_POST_MAX_SIZE=256M
      - HOME=/home/app
      - COMPOSER_HOME=/home/app/.composer
      - COMPOSER_CACHE_DIR=/home/app/.composer/cache
    volumes:
      - ./lucy:/app
    ports:
      - "8081:80"    # Apache (Laravel)
      - "5173:5173"  # Vite dev (opcional)

  # Los siguientes servicios ya no son necesarios con 'lucy' unificado.
  # Si los dejás, mantenelos apagados:
  # composer:
  #   image: composer:2
  #   user: "10001:10001"
  #   working_dir: /app
  #   environment:
  #     - HOME=/home/app
  #   volumes:
  #     - ./lucy:/app
  #   command: ["sleep", "infinity"]
  #
  # node:
  #   image: node:20
  #   working_dir: /app
  #   user: "10001:10001"
  #   environment:
  #     - HOME=/home/app
  #   volumes:
  #     - ./lucy:/app
  #   command: ["sleep", "infinity"]
