services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodlepass
      - MYSQL_ROOT_PASSWORD=rootpass
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./veco/db:/var/lib/mysql
    # ⬇️ Sin "ports:" para que NO quede expuesto fuera de Docker
    networks:
      campus:
        aliases:
          - veco-db   # Lucy/Samuel usarán DB_HOST=veco-db

  web:
    image: moodlehq/moodle-php-apache:8.2
    depends_on: [db]
    restart: unless-stopped
    environment:
      - MOODLE_DOCKER_DBTYPE=mariadb
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=moodlepass
    volumes:
      - ./veco/moodle:/var/www/html
      - ./veco/moodledata:/var/moodledata
    ports:
      - "8080:80"   # Moodle expuesto en el host
    networks: [campus]

  cron:
    image: moodlehq/moodle-php-apache:8.2
    depends_on: [web]
    restart: unless-stopped
    environment:
      - MOODLE_DOCKER_DBTYPE=mariadb
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=moodlepass
    volumes:
      - ./veco/moodle:/var/www/html
      - ./veco/moodledata:/var/moodledata
    entrypoint: ["bash","-lc","while true; do php /var/www/html/admin/cli/cron.php; sleep 60; done"]
    networks: [campus]

  pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on: [db]
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=0
      - UPLOAD_LIMIT=512M
    ports:
      - "8083:80"  # PhpMyAdmin (cambiá si 8083 está ocupado)
    networks: [campus]

networks:
  campus:
    external: true

